---
openapi: 3.0.1
info:
  title: Frames and Circles API
  version: v1
  description: API RESTful para cadastro e gerenciamento de quadros e círculos associados
paths:
  "/api/v1/frames/{frame_id}/circles":
    parameters:
    - name: frame_id
      in: path
      description: Frame ID
      required: true
      schema:
        type: integer
    get:
      summary: list circles
      tags:
      - Circles
      description: Lista todos os círculos de um quadro
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Circle"
        '404':
          description: frame not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
    post:
      summary: create circle
      tags:
      - Circles
      description: Cria um novo círculo no quadro
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Circle"
        '422':
          description: unprocessable entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                center_x:
                  type: number
                  format: float
                center_y:
                  type: number
                  format: float
                diameter:
                  type: number
                  format: float
              required:
              - center_x
              - center_y
              - diameter
  "/api/v1/circles/{id}":
    parameters:
    - name: id
      in: path
      description: Circle ID
      required: true
      schema:
        type: integer
    get:
      summary: show circle
      tags:
      - Circles
      description: Exibe um círculo específico
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Circle"
        '404':
          description: not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
    put:
      summary: update circle
      tags:
      - Circles
      description: Atualiza um círculo
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Circle"
        '404':
          description: not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
        '422':
          description: unprocessable entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                center_x:
                  type: number
                  format: float
                center_y:
                  type: number
                  format: float
                diameter:
                  type: number
                  format: float
    delete:
      summary: delete circle
      tags:
      - Circles
      description: Remove um círculo
      responses:
        '204':
          description: no content
        '404':
          description: not found
  "/api/v1/frames":
    get:
      summary: list frames
      tags:
      - Frames
      description: Lista todos os quadros
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Frame"
    post:
      summary: create frame
      tags:
      - Frames
      description: Cria um novo quadro
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Frame"
        '422':
          description: unprocessable entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                center_x:
                  type: number
                  format: float
                center_y:
                  type: number
                  format: float
                width:
                  type: number
                  format: float
                height:
                  type: number
                  format: float
              required:
              - center_x
              - center_y
              - width
              - height
  "/api/v1/frames/{id}":
    parameters:
    - name: id
      in: path
      description: Frame ID
      required: true
      schema:
        type: integer
    get:
      summary: show frame
      tags:
      - Frames
      description: Exibe um quadro específico com estatísticas
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Frame"
        '404':
          description: not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
    put:
      summary: update frame
      tags:
      - Frames
      description: Atualiza um quadro
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Frame"
        '404':
          description: not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
        '422':
          description: unprocessable entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                center_x:
                  type: number
                  format: float
                center_y:
                  type: number
                  format: float
                width:
                  type: number
                  format: float
                height:
                  type: number
                  format: float
    delete:
      summary: delete frame
      tags:
      - Frames
      description: Remove um quadro
      responses:
        '204':
          description: no content
        '404':
          description: not found
servers:
- url: http://localhost:3000
  description: Development server
components:
  schemas:
    Frame:
      type: object
      properties:
        id:
          type: integer
        center_x:
          type: number
          format: float
        center_y:
          type: number
          format: float
        width:
          type: number
          format: float
        height:
          type: number
          format: float
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - center_x
      - center_y
      - width
      - height
    Circle:
      type: object
      properties:
        id:
          type: integer
        center_x:
          type: number
          format: float
        center_y:
          type: number
          format: float
        diameter:
          type: number
          format: float
        frame_id:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - center_x
      - center_y
      - diameter
      - frame_id
    Error:
      type: object
      properties:
        error:
          type: string
        details:
          type: array
          items:
            type: string
